file_format: "1"
id: ergoTravelLight
name: Ergo Travel Light
type: shield
url: https://github.com/jpconstantineau/ErgoTravel
requires: [pro_micro]
features:
  - keys
siblings:
  - ergoTravelLight_left
  - ergoTravelLight_right